In [2]:
import numpy as np

In [3]:
# numpy array
# 存储顺序连续，尽可能存储同样类型的数据
tmp = np.array([1, 2, 3])
print(tmp)
print(type(tmp))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
import time

# python list
l = list(range(100))
print(len(l))
t0 = time.time()
for _ in range(10000):
    for i in range(len(l)):
        l[i] += 1

t1 = time.time()

# numpy array
n = np.array(list(range(100)))
print(len(n))
t2 = time.time()
for _ in range(10000):
    for i in range(len(n)):
        n[i] += 1
t3 = time.time()
print("Python list spend {:.3f}s".format(t1 - t0))
print("Numpy array spend {:.3f}s".format(t3 - t2))

100
100
Python list spend 0.140s
Numpy array spend 0.236s


In [5]:
# 创建多维数据
cars = np.array([5, 10, 12, 6])
print("数据：", cars, "\n维度：", cars.ndim)

cars = np.array([
[5, 10, 12, 6],
[5.1, 8.2, 11, 6.3],
[4.4, 9.1, 10, 6.6]
])

print("数据：\n", cars, "\n维度：", cars.ndim)

cars = np.array([
[
    [5, 10, 12, 6],
    [5.1, 8.2, 11, 6.3],
    [4.4, 9.1, 10, 6.6]
],
[
    [6, 11, 13, 7],
    [6.1, 9.2, 12, 7.3],
    [5.4, 10.1, 11, 7.6]
],
])
print("数据：\n", cars, "\n维度：", cars.ndim)
print("场地 1 数据：\n", cars[0], "\n场地 1 维度：", cars[0].ndim)
print("场地 2 数据：\n", cars[1], "\n场地 2 维度：", cars[1].ndim)

数据： [ 5 10 12  6] 
维度： 1
数据：
 [[ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]
 [ 4.4  9.1 10.   6.6]] 
维度： 2
数据：
 [[[ 5.  10.  12.   6. ]
  [ 5.1  8.2 11.   6.3]
  [ 4.4  9.1 10.   6.6]]

 [[ 6.  11.  13.   7. ]
  [ 6.1  9.2 12.   7.3]
  [ 5.4 10.1 11.   7.6]]] 
维度： 3
场地 1 数据：
 [[ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]
 [ 4.4  9.1 10.   6.6]] 
场地 1 维度： 2
场地 2 数据：
 [[ 6.  11.  13.   7. ]
 [ 6.1  9.2 12.   7.3]
 [ 5.4 10.1 11.   7.6]] 
场地 2 维度： 2


In [6]:
# 创建数组
tmp = np.zeros((2, 2, 3))
print(tmp)
print(tmp.shape)
print(tmp.ndim)
print(tmp.size)

tmp = np.ones((3, 2, 3))
print(tmp)
print(tmp.shape)
print(tmp.ndim)
print(tmp.size)

tmp = np.empty((2, 2, 3))
print(tmp)
print(tmp.shape)
print(tmp.ndim)
print(tmp.size)

tmp = np.arange(10, 100, 5)
print(tmp)
print(tmp.shape)
print(tmp.ndim)
print(tmp.size)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
3
12
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
(3, 2, 3)
3
18
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]
(2, 2, 3)
3
12
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
(18,)
1
18


In [7]:
# 访问数组
tmp = np.empty((3,4,5))
print(tmp.dtype)
# 索引
print(tmp[1][2][3])
# 切片
print(tmp[..., 0, :1])
# 迭代
for row in tmp:
    print(row.shape)
    for col in row:
        print(col.shape)

float64
7.788187155372276e-308
[[ 7.53754302e-312]
 [ 9.34608432e-307]
 [-9.22841825e-191]]
(4, 5)
(5,)
(5,)
(5,)
(5,)
(4, 5)
(5,)
(5,)
(5,)
(5,)
(4, 5)
(5,)
(5,)
(5,)
(5,)


In [8]:
# 同样支持广播操作
tmp = np.empty((2, 3, 4))
tmp1 = np.empty((3, 4))

print(tmp + tmp1)

[[[ 5.  10.  12.   6. ]
  [ 5.1  8.2 11.   6.3]
  [ 4.4  9.1 10.   6.6]]

 [[ 6.  11.  13.   7. ]
  [ 6.1  9.2 12.   7.3]
  [ 5.4 10.1 11.   7.6]]]


In [9]:
# 统计函数
# 数组所有元素是一元操作，通过指定的axis参数可以将擦欧总应用于数组的某一具体axis
print(tmp.mean())
print(tmp.mean(axis=1))
print(tmp.sum())
print(tmp.sum(axis=2))
print(tmp.min())
print(tmp.min(axis=0))
print(tmp.max())
print(tmp.max(axis=1))

8.308333333333332
[[ 4.83333333  9.1        11.          6.3       ]
 [ 5.83333333 10.1        12.          7.3       ]]
199.39999999999998
[[33.  30.6 30.1]
 [37.  34.6 34.1]]
4.4
[[ 5.  10.  12.   6. ]
 [ 5.1  8.2 11.   6.3]
 [ 4.4  9.1 10.   6.6]]
13.0
[[ 5.1 10.  12.   6.6]
 [ 6.1 11.  13.   7.6]]


In [10]:
# 全局函数
# 全局函数操作数组中每个元素，输出一个数组
print(np.sin(tmp))

[[[-0.95892427 -0.54402111 -0.53657292 -0.2794155 ]
  [-0.92581468  0.94073056 -0.99999021  0.0168139 ]
  [-0.95160207  0.31909836 -0.54402111  0.31154136]]

 [[-0.2794155  -0.99999021  0.42016704  0.6569866 ]
  [-0.1821625   0.22288991 -0.53657292  0.85043662]
  [-0.77276449 -0.62507065 -0.99999021  0.96791967]]]


In [11]:
# 操作形状
a = tmp.reshape((-1, 4, 2))
print(tmp)
a[0][0][0] = 100  # 会影响tmp
print(a)
print(tmp)
print(a.base is tmp)

[[[ 5.  10.  12.   6. ]
  [ 5.1  8.2 11.   6.3]
  [ 4.4  9.1 10.   6.6]]

 [[ 6.  11.  13.   7. ]
  [ 6.1  9.2 12.   7.3]
  [ 5.4 10.1 11.   7.6]]]
[[[100.   10. ]
  [ 12.    6. ]
  [  5.1   8.2]
  [ 11.    6.3]]

 [[  4.4   9.1]
  [ 10.    6.6]
  [  6.   11. ]
  [ 13.    7. ]]

 [[  6.1   9.2]
  [ 12.    7.3]
  [  5.4  10.1]
  [ 11.    7.6]]]
[[[100.   10.   12.    6. ]
  [  5.1   8.2  11.    6.3]
  [  4.4   9.1  10.    6.6]]

 [[  6.   11.   13.    7. ]
  [  6.1   9.2  12.    7.3]
  [  5.4  10.1  11.    7.6]]]
True


In [12]:
tmp.resize((3, 4, 2))
print(tmp)

[[[100.   10. ]
  [ 12.    6. ]
  [  5.1   8.2]
  [ 11.    6.3]]

 [[  4.4   9.1]
  [ 10.    6.6]
  [  6.   11. ]
  [ 13.    7. ]]

 [[  6.1   9.2]
  [ 12.    7.3]
  [  5.4  10.1]
  [ 11.    7.6]]]


In [13]:
# 拼接数组
# vstack()：垂直拼接
# hstack()：水平拼接 数组可以通过不同的 axes 组合起来。
a = np.floor(10 * np.random.random((2,2)))
b = np.floor(10 * np.random.random((2,2)))
print(np.vstack((a, b)))
print(np.hstack((a, b)))

[[3. 2.]
 [3. 2.]
 [5. 6.]
 [0. 8.]]
[[3. 2. 5. 6.]
 [3. 2. 0. 8.]]


In [14]:
# 拆分数组
# vsplit()：垂直拆分
# hsplit()：水平拆分
a = np.floor(10 * np.random.random((2, 12)))
print(np.hsplit(a, 3))

[array([[9., 7., 3., 4.],
       [4., 7., 7., 0.]]), array([[5., 0., 6., 6.],
       [9., 7., 6., 5.]]), array([[3., 9., 1., 8.],
       [2., 4., 1., 6.]])]


In [15]:
# 拷贝和视图
# 不拷贝：简单的赋值不会拷贝任何数组对象和他们的数据
# python将可变对象作为引用传递，函数调用不产生拷贝
# 视图和浅拷贝：不同的数组对象可以分享相同的数据
# view 方法创建了一个相同数据的新数组对象
# 切片等操作返回一个view
b = a.view()
print(b is a)
print(b.base is a)
print(b.flags.owndata)


False
True
False


In [16]:
# 深拷贝：
# copy：进行深拷贝
c = a.copy()
print(c is a)
print(c.base is a)
print(c.flags.owndata)

False
False
True


In [17]:
# 广播操作
img = np.empty((256, 256, 3))
scale = np.empty((3))
print((img + scale).shape)

img = np.empty((8, 1, 6, 1))
scale = np.empty((7, 1, 5))
print((img + scale).shape)

img = np.empty((5, 4))
scale = np.empty((1))
print((img + scale).shape)

img = np.empty((15, 3, 5))
scale = np.empty((15, 1, 1))
print((img + scale).shape)

(256, 256, 3)
(8, 7, 6, 5)
(5, 4)
(15, 3, 5)


In [18]:
# 高级索引
a = np.arange(12)**2
i = np.array([1, 2, 3, 1, 8, 5])
print(a[i])
j = np.array([[3, 4], [9, 7]])
print(a[j])

a = np.arange(12).reshape(3,4)
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])
print(a[i, j])

[ 1  4  9  1 64 25]
[[ 9 16]
 [81 49]]
[[ 2  5]
 [ 7 11]]


In [19]:
a = np.arange(12).reshape(3,4)
i = a > 4
print(i)
print(a[i])

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
